concert/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    path("", views.songs, name="songs"),
    path("", views.photos, name="photos"),
    path("", views.login_view, name="login"),
    path("", views.logout_view, name="logout"),
    path("", views.signup, name="signup"),
    path("", views.concerts, name="concerts"),
    path("concert-detail/<int:id>", views.concert_detail, name="concert_detail"),
    path("concert_attendee/", views.concert_attendee, name="concert_attendee"),
]

django_concert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("concert.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoserver/concert/urls.py
from django.urls import path
from . import views

app_name = 'concert'
urlpatterns = [
    path(route='', view=views.get_concert_list_view, name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('<int:pk>/', views.ConcertDetailView.as_view(), name='details'),
    path('<int:concert_id>/register/', views.register, name='concert_register'),
]

djangoserver/djangoserver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('concert/', include('concert.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

concert/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Concert(models.Model):
    # concert_name
    # duration
    # city
    # date

    def __str__(self):
        return self.concert_name


class ConcertAttending(models.Model):
    class AttendingChoices(models.TextChoices):
        NOTHING = "-", _("-")
        NOT_ATTENDING = "Not Attending", _("Not Attending")
        ATTENDING = "Attending", _("Attending")

    concert = models.ForeignKey(
        Concert, null=True, on_delete=models.CASCADE, related_name="attendee"
    )
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    attending = models.CharField(
        max_length=100,
        choices=AttendingChoices.choices,
        default=AttendingChoices.NOTHING,
    )

    class Meta:
        unique_together = ['concert', 'user']

    def __str__(self):
        return self.attending


class Photo(models.Model):
    # id
    # pic_url
    # event_country
    # event_state
    # event_city
    # event_date

    class Meta:
        managed = False

    def __str__(self):
        return self.pic_url


class Song(models.Model):
    # id
    # title
    # lyrics

    class Meta:
        managed = False

    def __str__(self):
        return self.title

djangoserver/concert/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now


# Create your models here.
class Song(models.Model):
    title = models.CharField(max_length=200, null=False)
    artist_name = models.CharField(max_length=100)
    length = models.IntegerField()
    pub_date = models.DateTimeField('publish date')
    image_url = models.CharField(max_length=256, null=True)
    genres = models.CharField(max_length=200, null=True)
    lyrics = models.CharField(max_length=1000)


class Concert(models.Model):
    title = models.CharField(max_length=200, null=False)
    songs = models.ManyToManyField(Song)
    poster = models.ImageField(upload_to='poster_images/')
    artist_name = models.CharField(max_length=100)
    total_registrations = models.IntegerField(default=0)
    release_date = models.DateTimeField('release date')
    is_registrated = False


class Registration(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    concert = models.ForeignKey(Concert, on_delete=models.CASCADE)
    date_registrated = models.DateField(default=now)

concert/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
                "name": "password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]


class SignUpForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
                "name": "password",
                "minlength": "3"
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]

concert/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.hashers import make_password

from concert.forms import LoginForm, SignUpForm
from concert.models import Concert, ConcertAttending
import requests as req


# Create your views here.

def signup(request):
    pass


def index(request):
    return render(request, "index.html")


def songs(request):
    # songs = {"songs":[]}
    # return render(request, "songs.html", {"songs": [insert list here]})
    pass


def photos(request):
    # photos = []
    # return render(request, "photos.html", {"photos": photos})
    pass

def login_view(request):
    pass

def logout_view(request):
    pass

def concerts(request):
    pass


def concert_detail(request, id):
    if request.user.is_authenticated:
        obj = Concert.objects.get(pk=id)
        try:
            status = obj.attendee.filter(user=request.user).first().attending
        except:
            status = "-"
        return render(request, "concert_detail.html", {"concert_details": obj, "status": status, "attending_choices": ConcertAttending.AttendingChoices.choices})
    else:
        return HttpResponseRedirect(reverse("login"))
    pass


def concert_attendee(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            concert_id = request.POST.get("concert_id")
            attendee_status = request.POST.get("attendee_choice")
            concert_attendee_object = ConcertAttending.objects.filter(
                concert_id=concert_id, user=request.user).first()
            if concert_attendee_object:
                concert_attendee_object.attending = attendee_status
                concert_attendee_object.save()
            else:
                ConcertAttending.objects.create(concert_id=concert_id,
                                                user=request.user,
                                                attending=attendee_status)

        return HttpResponseRedirect(reverse("concerts"))
    else:
        return HttpResponseRedirect(reverse("index"))

djangoserver/concert/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from .models import *
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import generic
import logging
from .restcalls import *

# Get an instance of a logger
logger = logging.getLogger(__name__)

base_lyric_service_url = "https://dummy.restapiexample.com/api/v1/employee/"

# Create your views here.
def get_concert_list_view(request):
    if request.method == "GET":
      # The context/data to be presented in the HTML template
      context = generate_concert_context(request)
      # Render a HTML page with specified template and context
      return render(request, 'concert/concert_list.html', context)


def check_is_registrated(user, concert):
    is_registrated = False
    if user.id is not None:
        # Check if user enrolled
        concert_counts = Registration.objects.filter(user=user, concert=concert).count()
        if concert_counts > 0:
            is_registrated = True
    return is_registrated


def generate_concert_context(request):
    context = {}
    concerts = Concert.objects.order_by('-total_registrations')[:30]
    for concert in concerts:
        current_user = request.user
        if current_user.is_authenticated:
            concert.is_registrated = check_is_registrated(current_user, concert)
    context['concert_list'] = concerts
    return context


def register(request, concert_id):
    concert = get_object_or_404(Concert, pk=concert_id)
    user = request.user
    is_enrolled = check_is_registrated(user, concert)
    if not is_enrolled and user.is_authenticated:
        # Create an enrollment
        Registration.objects.create(user=user, concert=concert)
        concert.total_registrations += 1
        concert.save()

    return HttpResponseRedirect(reverse(viewname='concert:details', args=(concert.id,)))


class ConcertDetailView(generic.DetailView):
    model = Concert
    template_name = 'concert/concert_detail_bootstrap.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        concert_id = self.kwargs['pk']
        concert = Concert.objects.get(pk=concert_id)
        for song in concert.songs.all():
            lyrics = get_lyrics(base_lyric_service_url, song.pk)
            print(lyrics)
            song.lyrics = lyrics
            song.save()
        context['concert'] = concert
        return context

def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'concert/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("concert:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'concert/user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('concert:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'concert/user_login_bootstrap.html', context)
    else:
        return render(request, 'concert/user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('concert:index')

djangoserver/concert/templates/concert/concert_detail_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
            <table class="table table-image">
              <thead>
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Image</th>
                  <th scope="col">Lyrics</th>
                  <th scope="col">Artist</th>
                  <th scope="col">Genres</th>
                  <th scope="col">Release Date</th>
                </tr>
              </thead>
              <tbody>
             {% for song in concert.songs.all %}
                <tr>
                  <th scope="row">{{ song.title }}</th>
                  <td class="w-25">
                      <img src={{ song.image_url }} class="img-fluid img-thumbnail" alt={{ song.title }}>
                  </td>
                  <td  class="w-25"><div style="height:240px;width:360px;border:1px solid #ccc;font:16px/26px Georgia, Garamond, Serif;overflow:auto;">
                      {{ song.lyrics }}
                  </div></td>
                  <td>{{ song.artist_name }}</td>
                  <td>{{ song.genres }}</td>
                  <td>{{ song.pub_date|date:"D d M Y" }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
    </body>
</html>

djangoserver/concert/templates/concert/concert_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <meta charset="UTF-8">
        <title>Concert List</title>
    </head>
    <!--Navigation bar-->
  <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="#">Popular Concert</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'concert:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'concert:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'concert:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <body>
    <!--Render concert list as card columns here -->
            <div class="container">
            <div class="card-columns">
                {% for concert in concert_list %}
                <div class="col-auto mb-3">
                    <div class="card">
                        <!--Concert Poster image-->
                        <img class="card-img-left"
                             src="{{MEDIA_ROOT}}/{{ concert.poster }}"
                             width="320" height="480">
                        <div class="card-body bg-light">
                            <h5 class="card-title">{{concert.title}}</h5>
                            <p class="card-text">{{concert.artist_name}}</p>
                            <p class="card-text">Enrollment: <b>{{concert.total_registrations}}</b></p>
                            <p class="card-text">{{concert.release_date}}</p>
                             <form action="{% url 'concert:concert_register' concert.id %}" method="post">
                                  {% csrf_token %}
                                  <input class="btn btn-primary"  type="submit"
                                         value="{% if concert.is_registrated %}Enter{% else %}Register{% endif %} ">
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>

</html>

djangoserver/concert/templates/concert/user_login_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'concert:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'concert:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'concert:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'concert:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Login form -->
    <form action="{% url 'onlinecourse:login' %}" method="post">
        {% csrf_token %}
        <div class="container"> <!--Style root div with .container class -->
            <h1>Login</h1>
            <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            </div>
            {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>

</body>

djangoserver/concert/templates/concert/user_registration_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Stylize Registration form -->
    <form action="{% url 'concert:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                {% if message %}
                <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>

</body>